name: Update Scores

on:
  push:
    paths:
      - 'Results.csv'
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-scores:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4
    - name: Run update script
      run: python generate_json.py
      env:
        RESULTS_FILE: Results.csv
    - name: Commit and push if changed
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add tournament_data.json
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update tournament data" && git push)
